CocoaPods/Core

- lib/cocoapods-core/specification/linter.rb
This has caused an error after updating the gem on trunk.
```diff
- "Missing required attribute `license`."
+ "Missing required attribute`license`."
```
This minor change fixes that and causes that the generated messages will be generated equal to the prior state, seen as above in red.
> Add the lost space preceding the attribute name in validation messages

- CHANGELOG.md
- lib/cocoapods-core/dependency.rb
- spec/dependency_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/3320.
\c @kylef
> [Dependency] Compact and ensure #external_source is not empty

- CHANGELOG.md
- lib/cocoapods-core/podfile.rb
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/standard_error.rb
- spec/standard_error_spec.rb
The new functionality is demonstrated at https://github.com/CocoaPods/Core/pull/226/files#diff-7dd13ddd3ab90c5487ed0e20928c423eR33
\c @kylef @orta
> [DSLError] Present fancy error messages even for things like SyntaxErrors that dont have cooperative backtraces

- CHANGELOG.md
- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/dsl_spec.rb
- spec/podfile/target_definition_spec.rb
Closes https://github.com/CocoaPods/Core/issues/221.
\c @kylef @orta @alloy
> [TargetDefinition] Allow specifying multiple subspec dependencies inline

- CHANGELOG.md
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/dsl/attribute.rb
- lib/cocoapods-core/specification/linter.rb
- lib/cocoapods-core/specification/linter/analyzer.rb
- spec/specification/dsl/attribute_spec.rb
- spec/specification/linter/analyzer_spec.rb
- spec/specification/linter_spec.rb
Includes a fix that `:root_only => true` attributes could been overwritten in subspecs.
Especially the change in a6d508f should been reviewed carefully.
/c @kylef @segiddins @alloy
> [Specification::DSL] Fixes around Linter and Analyzer

- lib/cocoapods-core/source.rb
- spec/source_spec.rb
I'd love to do this in a faster way, and in a manner that doesn't rely on `Pathname.glob`'s results matching the underlying preserved case.
\c @kylef @samdmarshall
Closes https://github.com/CocoaPods/CocoaPods/issues/3024.
Closes https://github.com/CocoaPods/CocoaPods/issues/2910.
> [Source] Make #search case sensistive even on case-insensitive HFS+

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/root_attribute_accessors.rb
- spec/specification/dsl_spec.rb
- spec/specification/root_attribute_accessors_spec.rb
- spec/specification_spec.rb
This pull request adds support for specifying a CocoaPods version inside the podspec (https://github.com/cocoapods/core/issues/240)
> Add support for cocoapods_version

- lib/cocoapods-core/specification/linter.rb
- spec/specification/linter_spec.rb
This fixes an issue with an exception being thrown when a local git URL is used as source. This is only really useful when you are writing tests with Rugged and Cocoapods to test our release process. 
If this is the source JSON:
```json
{:git=>"file:///tmp/d20150610-82513-1tuo9f7", :tag=>"builds/v1.0.0-b20131009151140"}
```
```ruby
perform_github_source_checks(s)
```
would throw an exception.
This is my first pull request against this repo, so please let me know if I forgot to do anything.
> fixed issue with exception being thrown when local git URL is used as source

- CHANGELOG.md
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/dsl/deprecations.rb
- spec/fixtures/BananaLib.podspec
- spec/specification/consumer_spec.rb
- spec/specification/dsl_spec.rb
- spec/specification_spec.rb
Belongs to CocoaPods/CocoaPods#3573.
> [WIP] Split xcconfig to pod_target_xcconfig and user_target_xcconfig

- CHANGELOG.md
- lib/cocoapods-core/platform.rb
- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/podfile/target_definition.rb
- lib/cocoapods-core/specification/dsl.rb
- spec/platform_spec.rb
- spec/specification/dsl_spec.rb
- spec/specification/linter_spec.rb
- spec/specification/set/presenter_spec.rb
This adds `watchos` as a platform to Core, meaning mostly that the DSL helpers are available. This lays the groundwork for supporting watchOS as a new platform in CocoaPods.
Things yet to be addressed:
See also CocoaPods/CocoaPods#3681 and CocoaPods/Xcodeproj#272
> Add `watchos` as a new platform

- lib/cocoapods-core/specification/linter.rb
- spec/specification/linter_spec.rb
With the new defaults from https://github.com/CocoaPods/pod-template/pull/129#issuecomment-131301753 and https://github.com/CocoaPods/CocoaPods/pull/3984 we provide an empty description instead of some meaningful starter text.
I've opted to make this an outright error if you don't include it, but a warning if it's shorter than the summary. Open to discussion around it, but it's pretty core metadata.
> [Linter] Show an error for an empty description

- lib/cocoapods-core/specification/dsl.rb
I want to improve the Guides for the DSLs. Currently they don't list the acceptable hash keys, there are only examples from which you can gleam this important information.
https://guides.cocoapods.org/syntax/podspec.html#source
I'm trying to find a good pattern to get this information into the documentation system, then we will also have to update **guides.cocoapods.org** to format and include it. Right now I'm just using `yard` to see how it picks up the comments.
Idealy, we shouldn't have to repeat ourselves. Where we define the options should be where the documentation is. I'm finding it hard to do this, and I'm not happy with the `@overload` usage here.
:bird: @orta
> Improve documentation for DSL attribute hash keys [RFC] [Guides]

- README.md
The old links do redirect to the new CocoaPods site, however, only to the guides page (https://guides.cocoapods.org), not the specific pages.
> [README] Update Podspec & Podfile syntax reference links

- CHANGELOG.md
- Gemfile.lock
- cocoapods-core.gemspec
When a user only has activesupport 3.2.15 installed, invoking `plugin` in a Podfile calls [`Hash.deep_stringify_keys`](http://apidock.com/rails/v4.0.2/Hash/deep_stringify_keys) causing a [crash](https://github.com/CocoaPods/CocoaPods/issues/3076).  `deep_stringify_keys` was first added to activesupport in version 4.0.2, but the base version required by core is 3.2.15. As noted in the comments on Cocoapods/Cocoapods#2307, the base activesupport version was held back to continue support for versions of Ruby before 2.0.0.
As of 76845c8, Cocoapods no longer supports Ruby versions less than 2.0, invalidating the reasoning for holding back the base version number.
> Change required activesupport version to >=4.0.2

- lib/cocoapods-core/podfile/dsl.rb
Added documentation of the implicit source of the official CocoaPods specs repo.
I also removed the explicit CocoaPods source line from the 'very basic' example of Podfiles.
Thanks for the help @orta
> Added documentation of implicit `source` in Podfile docs

- CHANGELOG.md
- lib/cocoapods-core/source.rb
- lib/cocoapods-core/source/aggregate.rb
- spec/source/aggregate_spec.rb
- spec/source_spec.rb
Detailed discussion can be found here: CocoaPods/cocoapods-search#8
- Previous implementation was having the drawback of traversing and performing `gsub` on all index strings for each pod specification.
- New implementation stores words as keys and list of pods containing corresponding word inside their specification as the values for corresponding hash keys. By this way, sources manager can perform a faster search operation.
> Changes search index format to fasten `pod search --full` command.

- lib/cocoapods-core/specification/dsl.rb
Indentation made the docs parser ignore it
> Fix CocoaDocs Podspec `cocoapods_version` example not showing

- CHANGELOG.md
- lib/cocoapods-core/dependency.rb
- lib/cocoapods-core/podfile/target_definition.rb
- lib/cocoapods-core/source.rb
- lib/cocoapods-core/specification.rb
- spec/dependency_spec.rb
This adds the ability to add a `:source` flag to pod dependencies in a Podfile. This behavior mirrors in [Gemfiles](http://bundler.io/gemfile.html), allowing a dependency to be specified as such:
`pod 'JSONKit', '1.4', :source => 'http://github.com/MyOrg/Specs.git'`
This is a prerequisite for https://github.com/CocoaPods/CocoaPods/pull/4486
> Add ability to specify an explicit source for a given dependency

- lib/cocoapods-core/yaml_helper.rb
I have internal packages with unfortunately long names.
This, though, causes CocoaPods to generate lock files it can't read, since it
wraps in such a way as to not be valid YAML anymore.
> Don't Wrap Long Lines

- lib/cocoapods-core/specification/dsl.rb
Recommends using `deployment_target` when there is a need to define multiple platforms.
> [DSL] improve docs on platfrom attribute for a spec

- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/specification/dsl.rb
I'm still a bit unsure about a lot of these kind of docs:
```
```
> Documentation for Podfile Refactor

- CHANGELOG.md
- lib/cocoapods-core/dependency.rb
- lib/cocoapods-core/lockfile.rb
- lib/cocoapods-core/podfile.rb
- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/podfile/target_definition.rb
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/dsl/deprecations.rb
- lib/cocoapods-core/specification/json.rb
- lib/cocoapods-core/version.rb
- spec/dependency_spec.rb
- spec/fixtures/Podfile.yaml
- spec/lockfile_spec.rb
- spec/podfile/dsl_spec.rb
- spec/podfile/target_definition_spec.rb
- spec/podfile_spec.rb
- spec/specification/dsl/deprecations_spec.rb
- spec/specification/json_spec.rb
- spec/specification_spec.rb
- spec/version_spec.rb
This part of the podfile refactor is pretty much done.
Closes https://github.com/CocoaPods/Core/issues/151.
> Podfile Refactor

- CHANGELOG.md
- lib/cocoapods-core/dependency.rb
Fixes #291.
This check was failing for lockfile entries like `Expecta (HEAD based on 1.0.5)`. We should if entry actually includes `HEAD`
> [Dependency] Fix obsolete HEAD string check for lockfile entries

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/dsl_spec.rb
- spec/podfile/target_definition_spec.rb
- spec/podfile_spec.rb
This enables setting `:inhibit_warnings => false` option to pods in podfile.
Warnings from pods having above value will not surpass even if `inhibit_all_warnings!` is set.
> Add ability to disable inhibiting warnings per pod

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/target_definition_spec.rb
`false` values were set to nil, when they were read, so that `use_frameworks?` would be evaluated to `true` on the next access.
> [TargetDefinition] Safe access for bool values

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/dsl.rb
- spec/specification/dsl_spec.rb
- spec/specification/linter_spec.rb
> [Specification DSL] default_subspecs is only allowed at root level

- lib/cocoapods-core/podfile/dsl.rb
I noticed this typo, but it seemed to include old, no longer relevant information (as the site has been deprecated and changed to guides.cocoapods.org).
> [Docs] Typo and outdated link

- CHANGELOG.md
- lib/cocoapods-core/specification/consumer.rb
Allows scoping root-only attributes per-platform, and cleaning up some usage of the spec consumer.
> [TargetDefinition] Allow inheriting root-only attributes

- CHANGELOG.md
- lib/cocoapods-core.rb
- lib/cocoapods-core/github.rb
- lib/cocoapods-core/master_source.rb
- lib/cocoapods-core/source.rb
- lib/cocoapods-core/source/aggregate.rb
- spec/fixtures/vcr_cassettes/GitHub.yml
- spec/fixtures/vcr_cassettes/MasterSource_fetch.yml
- spec/fixtures/vcr_cassettes/MasterSource_nofetch.yml
- spec/github_spec.rb
- spec/master_source_spec.rb
- spec/source/aggregate_spec.rb
- spec/source_spec.rb
- spec/specification/set/presenter_spec.rb
- spec/specification/set_spec.rb
As recommended https://github.com/CocoaPods/CocoaPods/issues/4989#issuecomment-193801376
Supersedes https://github.com/CocoaPods/CocoaPods/pull/5001
CocoaPods/CocoaPods counterpart: https://github.com/CocoaPods/CocoaPods/pull/5014
> Check the GitHub API before Fetching the Master Specs repo

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods-core/core_ui.rb
- lib/cocoapods-core/source.rb
- lib/cocoapods-core/source/aggregate.rb
- lib/cocoapods-core/source/manager.rb
- lib/cocoapods-core/source/metadata.rb
- spec/fixtures/spec-repos/test_prefixed_repo/CocoaPods-version.yml
- spec/fixtures/spec-repos/test_prefixed_repo/Specs/1/3/f/JSONKit/1.13/JSONKit.podspec
- spec/fixtures/spec-repos/test_prefixed_repo/Specs/1/3/f/JSONKit/1.4/JSONKit.podspec
- spec/fixtures/spec-repos/test_prefixed_repo/Specs/1/3/f/JSONKit/999.999.999/JSONKit.podspec
- spec/fixtures/spec-repos/test_prefixed_repo/Specs/3/8/e/BananaLib/0.0.1/BananaLib.podspec
- spec/fixtures/spec-repos/test_prefixed_repo/Specs/3/8/e/BananaLib/0.9/BananaLib.podspec
- spec/fixtures/spec-repos/test_prefixed_repo/Specs/3/8/e/BananaLib/1.0/BananaLib.podspec
- spec/fixtures/spec-repos/test_prefixed_repo/Specs/9/0/c/IncorrectPath/1.0/IncorrectPath.podspec
- spec/fixtures/spec-repos/test_prefixed_repo/Specs/d/8/d/JSONSpec/0.9/JSONSpec.podspec.json
- spec/fixtures/spec-repos/test_prefixed_repo/Specs/d/8/d/JSONSpec/1.0/JSONSpec.podspec.json
- spec/master_source_spec.rb
- spec/source/manager_spec.rb
- spec/source/metadata_spec.rb
- spec/source_spec.rb
- spec/spec_helper.rb
- spec/spec_helper/temporary_directory.rb
In doing so, we've migrated `Pod::SourcesManager` from CocoaPods/CocoaPods as a singleton to be a proper class, and also added support for sharded specs directories.
Fixes https://github.com/CocoaPods/CocoaPods/issues/5062.
> Introduce Source::Metadata

- CHANGELOG.md
- lib/cocoapods-core/source/aggregate.rb
- lib/cocoapods-core/source/manager.rb
- spec/source/aggregate_spec.rb
- spec/source/manager_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/5031.
This is needed because JSON does not support getting values as symbols during parse.
> [Aggregate] Convert search index value types to string

- CHANGELOG.md
- lib/cocoapods-core/github.rb
- spec/master_source_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/5175
Not sure if just warning and returning false is correct, because at that point it's an actual failure of `pod repo update`
> GitHub error handling

- lib/cocoapods-core/podfile/dsl.rb
This removes an old remark that shouldn't be there anymore considering 1.0 and adds a new one on the handling of transitive dependencies when using build configurations.
> Update docs for build configurations

- lib/cocoapods-core/podfile/dsl.rb
It was not clear to me when reading that what the first parameter was meant to be, if it was always meant to be `'cocoapods'` or if other values might be acceptable, etc, hence this more specific documentation.
> Improve documentation for Podfile's 'install!' attribute

- CHANGELOG.md
- lib/cocoapods-core/podfile/dsl.rb
- spec/podfile/dsl_spec.rb
A lot of my coworkers and friends saw the "xcodeproj was renamed to project" warning but thought it was a warning inside CocoaPods' own code, like some warning aimed at us and that we'd have to fix in the future.
They didn't understand that it was meant to suggest that **they** should update their `Podfile` to fix it. Hence that new message to make things clearer.
> Improved warning message for DSL attribute renaming

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl.rb
to reduce doc pollution, as discussed in Slack.
> Removed reference of OS_OBJECT_USE_OBJC from deployment_target doc

- CHANGELOG.md
- lib/cocoapods-core/source/manager.rb
Before:
```
$ pod search foobar
[!] Unable to find a pod with name, author, summary, or descriptionmatching `foobar`
```
After:
```
$ pod search foobar
[!] Unable to find a pod with name, author, summary, or description matching `foobar`
```
> Add missing space to not-found message

- CHANGELOG.md
- lib/cocoapods-core/podfile/dsl.rb
- spec/podfile/dsl_spec.rb
Fixes https://github.com/CocoaPods/CocoaPods/issues/5474
> [DSL] Raise when specifying multiple post_install hooks

- lib/cocoapods-core/podfile/dsl.rb
🌈
There is a discrepancy between the example for post_hook and the "complex" example on the main Podfile Syntax Reference
> [docs] example on main Podfile section is invalid

- CHANGELOG.md
- lib/cocoapods-core/version.rb
- spec/version_spec.rb
Fixes CocoaPods/CocoaPods#5718
- Handle special case of missing first segment of pre-release segments (doesn't mean it wasn't handled before, just calling out this part in the diff)
- Updated according to [Semver's predence spec](http://semver.org/#spec-item-11) (item 11 if it doesn't link you straight there):
> Numeric identifiers always have lower precedence than non-numeric identifiers.
> Improved handling of Semver pre-release versions

- lib/cocoapods-core/master_source.rb
- lib/cocoapods-core/source.rb
- spec/master_source_spec.rb
- spec/source_spec.rb
This removes all of the git-related `Dir.chdir`s. There's only one left, but I'm not sure that one is as easy to circumvent? This fixes issues related to CocoaPods not being able to find source repos and trying to re-create existing ones.
> Use git -C instad of Dir.chdir

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/target_definition_spec.rb
- spec/podfile_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/5342
> Raise an error if `inherit!` is used on an abstract target

- CHANGELOG.md
- lib/cocoapods-core/version.rb
- spec/version_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/6224
implemented as per the specification: http://semver.org/#spec-item-10
Fortunately this doesn't actually effect comparison, so is a reasonably easy
change to make by dropping it from comparable segments, but maintaining it for
display.
> [Pod::Version] Add support for build metadata

- lib/cocoapods-core/specification.rb
- spec/specification_spec.rb
Ensures that newlines are stripped for `Specification#version`. This was a regression in #358 that broke CocoaPods/CocoaPods integration tests with `RealmSwift.podspec`.
> Strip newlines for Specification#version

- CHANGELOG.md
- lib/cocoapods-core/specification/linter.rb
- spec/specification/linter_spec.rb
This fixes a crash when there is a `description` but no `summary`.
closes https://github.com/cocoapods/cocoapods/issues/6360
> [Linter] Check for presence of `summary` when validating descriptions

- lib/cocoapods-core/specification/dsl.rb
Fixes #371.
The pod creator should be aware of [what will happen to the headers files in Xcode build phases](https://github.com/CocoaPods/CocoaPods/blob/8df7c49a783ab1661e8e1b532f7725a1604c2c39/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L403).
> Clarify the existance of public, private and project headers

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/linter.rb
- spec/specification/consumer_spec.rb
- spec/specification/dsl_spec.rb
- spec/specification/linter_spec.rb
- spec/specification_spec.rb
I'd like to re-open the "project" for adding test support to CocoaPods. 
We have 100s of projects that we typically end up having to include a `<ProjectName>Tests.xcodeproj` that includes all of our test sources and a `Podfile` that integrates it with the pod locally.
I've chatted with @orta and @benasher44 on bringing this back. It would be awesome for podspecs to become more self-contained and when consumed as development pods the `Pods.xcodeproj` can create a test bundle target to include test sources so you can run them.
We are also heavy users of development pods in our main project causing us to create multiple xcodeproj just to support our tests for pods we will never publish which also complicates CI further.
This is the first PR that brings back the DSL to include a `test_spec`. …
> Introduce `test_specification` DSL

- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/json.rb
- lib/cocoapods-core/specification/linter.rb
- spec/specification/consumer_spec.rb
- spec/specification/json_spec.rb
- spec/specification/linter_spec.rb
- spec/specification_spec.rb
I've started a bit of integration with the cocoapods project to add test targets into the project.
So far I've hit a couple of things that are needed to be fixed in the core which are requested here.
> Ensure test_specification is part of the attributes hash

- .gitignore
- .travis.yml
- lib/cocoapods-core/github.rb
- lib/cocoapods-core/master_source.rb
- lib/cocoapods-core/source.rb
- spec/github_spec.rb
- spec/master_source_spec.rb
- spec/source/manager_spec.rb
- spec/source_spec.rb
Applies the GitHub efficiency check added in https://github.com/CocoaPods/Core/pull/313 to any spec repo which is hosted on GitHub.
Wanted to check approach before I add specs (i.e., move them from the ones currently on `MasterSource`). Are you guys OK with the above in principle, and do you see any reason for the continuing existence of `MasterSource` once it's done?
> Apply GitHub checking logic to all GitHub hosted sources

- .travis.yml
- Gemfile
- Gemfile.lock
- cocoapods-core.gemspec
Having looked through the previous conversation on locking ActiveSupport in CocoaPods ([here](https://github.com/CocoaPods/CocoaPods/pull/5602)) I can't see any reason why it should be locked in Core, too. Specs were previously failing on `2.0.0-p481`, which had a buggy version of Bundler on Travis (presumably the same buggy version which was causing the issue on clean installs in the first place), but I think it should be fine to unlock the gem here and just fix the spec setup. Won't affect CocoaPods since that has a tighter specification in its gemspec.
> Allow ActiveSupport 5+

- CHANGELOG.md
- lib/cocoapods-core/lockfile.rb
- spec/lockfile_spec.rb
Strange quotation marks in 'SPEC CHECKSUMS' section
```
SPEC CHECKSUMS:
SDWebImage: '098e97e6176540799c27e804c96653ee0833d13c'
```
> Fix Strange quotation marks in `lockfile.rb`

- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/target_definition_spec.rb
```ruby
pod 'SamplePod', :path => 'SamplePod.podspec', :testspecs => ['Tests']
```
:D
> Handle :testspecs DSL for pod dependencies

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/target_definition_spec.rb
> Correctly include parent dependencies when parsing testspecs

- CHANGELOG.md
- lib/cocoapods-core/source.rb
- lib/cocoapods-core/version.rb
- spec/source_spec.rb
The bigger our internal repo gets the more version comparisons occur. I profiled and saw a 17-20% increase by caching those results which seem safe to cache.
Here's a medium size project 17% improvement.
```
Before:
real	0m10.410s
user	0m9.156s
sys	0m0.772s
After:
real	0m8.642s
user	0m7.322s
sys	0m0.866s
```
There is another PR I will do in the main project.
> Cache version result for each pod and segments

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
See https://github.com/CocoaPods/CocoaPods/pull/6810 for profiling and why this helps!
> Cache target definition label value

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl.rb
According to current implementation of downloader https://github.com/CocoaPods/cocoapods-downloader/blob/978dfcd59e028db875cd4bb191ebbf3195b6fc26/lib/cocoapods-downloader.rb#L21-L29 the `:path` key is not supported for `spec.source` and the doc available [here](https://guides.cocoapods.org/syntax/podspec.html#source) is misleading.
Couple of related issues:
https://github.com/CocoaPods/CocoaPods/issues/4937
https://github.com/CocoaPods/cocoapods-packager/issues/32
// disclaimer
I quite far away from ruby development and mostly do mobile. Please let me know if there any more places where this should be cleaned up.
Thanks for great tool.
> Update DSL for `spec.source`

- .travis.yml
- README.md
Just cosmetics. The [gemspec](https://github.com/CocoaPods/Core/blob/master/cocoapods-core.gemspec#L31) actually already require Ruby 2.0.0 or greater.
> Update travis.yml with latest Ruby, and fix README

- lib/cocoapods-core/source.rb
- spec/source_spec.rb
This makes `unchanged_github_repo?` use the pre-exisiting `url` method
for retreiving the source URL, and stubs this in the tests, as
previously we were pointing to a github repo here, which is:
a) not the goal of the test
b) doing networking during tests (which is 😢 and breaks working on CocoaPods offline)
> Fix source specs

- CHANGELOG.md
- lib/cocoapods-core/specification/linter.rb
- lib/cocoapods-core/specification/root_attribute_accessors.rb
- spec/fixtures/spec-repos/test_repo/Specs/BananaLib/0.8/BananaLib.podspec
- spec/source/health_reporter_spec.rb
- spec/specification/root_attribute_accessors_spec.rb
This fixes https://github.com/CocoaPods/CocoaPods/issues/6701.
Add a warning if the strings` 'true'` or `'false' ` are being used instead of boolean `true` or `false`  as the value for 'requires_arc' in the pod spec file.
> Check requires arc true false strings

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/root_attribute_accessors.rb
- spec/specification/dsl_spec.rb
- spec/specification/root_attribute_accessors_spec.rb
Introduce static_framework podspec attribute to indicate that a source CocoaPod should be built into a static library framework. 
More details in the corresponding CocoaPods PR - coming shortly.
> Static framework

- CHANGELOG.md
- lib/cocoapods-core/specification/json.rb
- spec/specification/json_spec.rb
- spec/specification/linter_spec.rb
This fixes an issue where older versions of CocoaPods parse a podspec in JSON that was created and includes a test spec.
The end result is that the old version would treat the test spec as a subspec and attempt to load and link all test dependencies as normal dependencies.
This separation prevents this but it does create a separation and concern between 1.3.0 and 1.3.1. 1.3.1 *will* support 1.3.0 podspecs and then from now and on split the hash when serialized.
> Split testspecs from subspecs during JSON serialization

- lib/cocoapods-core/yaml_helper.rb
- spec/yaml_helper_spec.rb
This should fix https://github.com/CocoaPods/CocoaPods/issues/6925 regardless of the ruby/psych being used.
I went for an overly conservative approach (that is, more strings might be quotes than necessary), but I think given the structure of lockfiles this should cause minimum disruption from the status quo.
> [YAMLHelper] Implement consistent string processing

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/target_definition_spec.rb
🌈
Found an issue where the requirements weren't being deep copied when using the `:testspecs` directive in combination with the `:configurations` directive. It would lead to an error message showing up with:
> [!] The subspecs of `MyPod` are linked to different build configurations for the `Pods-MyApp` target. CocoaPods does not currently support subspecs across different build configurations.
This addresses the issue by deep copying the requirements Hash contained within the Array instead of just copying the array containing those requirements.
> Fix requirements cloning for `:testspecs`

- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/podfile/target_definition.rb
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/linter.rb
- spec/podfile/target_definition_spec.rb
- spec/specification/consumer_spec.rb
- spec/specification/json_spec.rb
- spec/specification/linter_spec.rb
- spec/specification_spec.rb
@paulb777 I won't get into the habit of adding you as a reviewer. First of all thanks for your time on these and second it's only because you've reviewed the other PRs.
> Extend script phase DSL to support execution position

- CHANGELOG.md
- lib/cocoapods-core/source.rb
- lib/cocoapods-core/specification/set.rb
- spec/specification/set_spec.rb
Within `source.rb`, just by calling:
```ruby
def search(query)
unless specs_dir
raise Informative, "Unable to find a source named: `#{name}`"
end
if query.is_a?(Dependency)
query = query.root_name
end
found = Pathname.glob(pod_path(query)).map { |path| path.basename.to_s }
if [query] == found
set = set(query)
set if set.specification.name == query # <----------------- this line
end
end
```
It calls `Pod::Specification::Set#specification` which will call twice the expensive `highest_version_spec_path` method.
There is no need for us to get the highest version spec if the only thing we need is the name of the specification, which should not be any different given all Podspec names are unique.
This actually saves about 7%-9% in `pod install` time for a large project that contains a specific …
> Improve performance of `Pod::Source#search`

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
...ironically the branch name used has a typo. ¯\\\_(ツ)_/¯
> Fix typo when validating cocoapods version

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/root_attribute_accessors.rb
- spec/specification/dsl_spec.rb
- spec/specification/root_attribute_accessors_spec.rb
Relates to: https://github.com/CocoaPods/CocoaPods/issues/7134
> [Podspec] Add `swift_version` DSL

- lib/cocoapods-core/source.rb
- spec/master_source_spec.rb
- spec/source_spec.rb
GIT_CONFIG is an environment variable that overrides which files `config
--get` actually fetches from. The benefit in setting this is that if you
want to add configuration, you don't have to use `--global`. I would
never recommend anyone set this, but in the case that you do, CocoaPods
can never find local specs repos by matching URLs, since getting
remote.origin.url will come from a different file, and likely always be
empty.
There's a `--local` flag that is also supposed to be the opposite of
`--global` for this, but setting this when GIT_CONFIG is set results in
an error. The other option would be to pass the file explicitly with
`--file .git/config`, but this feels more fragile.
> Unset GIT_CONFIG when running commands

- CHANGELOG.md
- lib/cocoapods-core/http.rb
- spec/http_spec.rb
Uses a GET request with a 1 byte Range header if the initial HEAD request fails. Falls back to a GET request without a Range header if that also fails.
Closes #420
I've added the GET request with a Range header as an additional fallback and kept the original non-Range GET request as the final fallback. This is because I wasn't sure if we should expect that a server might respond to a normal GET request but return an error if the GET request includes a Range header.
My intuition would say that almost all servers that don't respond to a Range header would just ignore it and proceed as if it didn't exist. In this case, we wouldn't need the third non-Range fallback. Do we think this is a case that we would want to support? Having all 3 is the more conservative route, but adds additional …
> Add Range header to HTTP::perform_head_request

- lib/cocoapods-core/lockfile.rb
- spec/lockfile_spec.rb
Fixes a bug in an unreleased feature, hence no CHANGELOG
> [Lockfile] Only put root spec names under SPEC REPOS

- CHANGELOG.md
- lib/cocoapods-core/source.rb
- spec/source_spec.rb
Fix https://github.com/CocoaPods/CocoaPods/issues/6381
If a source spec directory has had all of its version subdirectories removed, `pod install` would crash with `TypeError - no implicit conversion of nil into String` at `cocoapods-core/specification.rb:584`.
The empty directory would occur if a Spec repo previously had one or more versions of a particular pod and then all of the versions were removed.
The workaround was to delete ~/.cocoapods/repos/{repo}/ or just the offending empty directory.
> Fix crash when there's an empty source spec directory

- CHANGELOG.md
- lib/cocoapods-core/lockfile.rb
- lib/cocoapods-core/yaml_helper.rb
- spec/yaml_helper_spec.rb
even if it means there are some quotes
Some things simply cannot exist as plain, unquotes scalars in YAML. Instead of blindly stripping all quotes from the generated lockfile, we are instead more conservative when quoting string during generation. We still quote more than is technically necessary according to the YAML spec, but this is about as accurate as I was willing to get.
Closes https://github.com/CocoaPods/CocoaPods/issues/7302 by partially reverting https://github.com/CocoaPods/Core/pull/381/files
> [Lockfile] Always serialize as valid YAML

- lib/cocoapods-core/lockfile.rb
By using a Hash instead of Array#find, this becomes O(n) rather than O(n^2)
Additionally, we no longer need to call Podfile#dependencies once per dependency name, which is huge since that list of dependencies gets recomputed on each call
> [Lockfile] Improve performance of #detect_changes_with_lockfile

- lib/cocoapods-core/specification/dsl.rb
As brought up in [#5192](https://github.com/CocoaPods/CocoaPods/issues/5192), the documentation for preferring the use of `resource_bundles` over `resources` is outdated with the integration of frameworks. Seemed like @orta and @neonichu agreed on updating the docs so here's my crack at it.
tl;dr I specified that using `resource_bundles` is preferred for Pods that are built as static libraries.
> [Specification] Update resource_bundles documentation for usage recommendation ambiguity 🌈

- lib/cocoapods-core/specification/dsl.rb
- spec/specification/dsl_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/7576
I've definitely made the same mistake before.
> Provide a helpful error message when attempting to assign a value to `dependency`

- CHANGELOG.md
- lib/cocoapods-core/podfile.rb
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile_spec.rb
This makes writing tests for objects that hold Podfiles much easier
> [Podfile] Implement ==

- CHANGELOG.md
- lib/cocoapods-core/podfile.rb
- lib/cocoapods-core/specification.rb
closes https://github.com/CocoaPods/CocoaPods/issues/7854
On a large project I noticed this gets called multiple times for the same specification which can be costly.
/cc @Whirlwind
> Cache result of `Specification#checksum` and `Podfile#checksum` methods

- lib/cocoapods-core/version.rb
- spec/dependency_spec.rb
- spec/specification_spec.rb
- spec/version_spec.rb
It's been 2 years since they were removed, and this saves a regexp match on every version allocation
> [Version] Stop parsing legacy HEAD versions

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/fixtures/BananaLib.podspec
- spec/fixtures/BananaLib.podspec.json
- spec/podfile/dsl_spec.rb
- spec/podfile/target_definition_spec.rb
- spec/specification/json_spec.rb
- spec/specification_spec.rb
Sometimes, I use the `podspec` in a Podfile to load dependencies from a `.podspec` file. But I often just load one or some subspec(s) from the podspec file, not load all dependencies.
eg: this is a Podspec:
```
s.dependency 'SDWebImage'
s.subspec 'ASI' do |s1|
s1.dependency 'ASIHTTPRequest'
end
s.subspec 'AF' do |s2|
s2.dependency 'AFNetworking'
end
```
this is a Podfile:
```
target :SDKForASI do
podspec :subspec=>'ASI'
end
target :SDKForAF do
podspec :subspec=>'AF'
end
```
I need the target have different dependencies from different subspecs. This PR will add a option `subspec`(`subspecs`) to the `podspec` DSL.
> Use the `podspec :subspec=>'xx'` to load dependencies from a subspec

- CHANGELOG.md
- lib/cocoapods-core/source/manager.rb
- spec/source/manager_spec.rb
Forks are not supported on windows - making sure we don't crash
> Windows support

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/dsl/attribute.rb
In preparation of scheme support and now that we have app specs and test specs.
> Replace `test_only` attribute option with `spec_types`.

- lib/cocoapods-core/podfile/dsl.rb
* lib/cocoapods-core/podfile/dsl.rb: Extend the version explanations
to cover the behavior for more complex version numbering schemes
within semantic versioning.
> Explain Handling of dash-separated Version Components

- CHANGELOG.md
- lib/cocoapods-core/lockfile.rb
- lib/cocoapods-core/yaml_helper.rb
- spec/lockfile_spec.rb
I've tried running `pod install --deployment` and it was erroring out on pod GoogleSignIn and its deps.  
Upon debugging this I've found a bug in the diff algorithm that I'm submitting a patch for.
I've made a demo project at [igor-makarov/Demo-CocoaPods-GoogleSignIn](https://github.com/igor-makarov/Demo-CocoaPods-GoogleSignIn/blob/20f7d1228a1f6277d5734ce67021d2aa6afde9e9/.travis.yml#L15).
I've also attached the [Travis build log](https://travis-ci.org/igor-makarov/Demo-CocoaPods-GoogleSignIn/builds/468356059) that shows the command run with/without the patch.
EDIT: The complementary PR in main CP repo wasn't necessary so I closed it.
> Fix --deployment flag incorrectly erroring on GoogleSignIn

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl.rb
- spec/specification/dsl_spec.rb
Improves the error message ’Unsupported version requirements' if it is caused by specifying :git or :path in the podspec file.
> Improve error messages  for podspec dependencies

- lib/cocoapods-core/source/manager.rb
- spec/source/manager_spec.rb
This PR resolves a bug I was having because I've switched to the new [CDN-source](https://github.com/CocoaPods/Core/pull/469) and had an error.
The error happened because while the Podfile had the new source specified, the Podfile.lock still had the old source and I have deleted the old source.  
I've gotten around it by manually hacking the lockfile, but clearly this isn't the right way.
I've modified the `aggregate_for_dependency` method in a way that preserves current behavior but in the case of not being able to find the specified source for the dependency, it will default to all sources. 
I've added a test for the case.
> Source::Manager - return all aggregate sources if the dependency's spec repo doesn't exist

- .travis.yml
- CHANGELOG.md
- lib/cocoapods-core/specification/consumer.rb
- spec/specification/consumer_spec.rb
In https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L289...
...we now use the consumer of the spec to read the value. Unfortunately the value that comes back from the consumer for JSON podspecs can be a string which cascades into other failures.
This fixes this and all subsequent callsites.
> Ensure `test_type` value is converted to a symbol from consumer

- lib/cocoapods-core/specification/dsl.rb
Closes https://github.com/CocoaPods/guides.cocoapods.org/issues/18
The documentation for this attribute seems pretty substantial, this adds the last item
mentioned on that issue.
> Add namespace to example resource bundle for consistency with documentation

- CHANGELOG.md
- lib/cocoapods-core/podfile/dsl.rb
> Add documentation for `:testspecs` option on Podfile `pod` DSL

- lib/cocoapods-core/cdn_source.rb
- spec/cdn_source_spec.rb
I've been testing CDNSource myself for a while now and I think that I can make it a bit more optimistic.
When running `pod install`, it will assume that all existing files do not need updating.
To update the existing files, a run of `pod repo update` will be needed, but `pod update` runs it by default.
> Change CDNSource to be optimistic

- lib/cocoapods-core/cdn_source.rb
- spec/cdn_source_spec.rb
Today, an outage has started happening on jsDelivr's network and CDNSource didn't provide any constructive feedback.
Furthermore, I noticed that there's no distinction between expected errors (404) and unexpected errors (5XX).
This PR adds proper error handling to CDNSource.  
I've added a test for the error 500 case and also refined the 404 tests to check for the error.
> CDNSource: Raise error on unexpected HTTP errors + add/improve tests

- CHANGELOG.md
- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/specification/dsl.rb
- spec/podfile/target_definition_spec.rb
- spec/specification/linter_spec.rb
Prerequisite for https://github.com/CocoaPods/CocoaPods/pull/8585
> Add support for `xcfilelist` in `script_phase` DSL

- CHANGELOG.md
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/linter.rb
- spec/specification/consumer_spec.rb
- spec/specification/linter_spec.rb
This supports a forthcoming PR in cocoapods/cocoapods to specify an
existing app spec to use as a test spec app host instead of generating
one on the fly.
> Add `test_spec. app_host_name` to DSL

- CHANGELOG.md
- lib/cocoapods-core/specification/linter.rb
- lib/cocoapods-core/specification/linter/analyzer.rb
- lib/cocoapods-core/specification/root_attribute_accessors.rb
- spec/specification/linter_spec.rb
Closes CocoaPods/CocoaPods#5420
> Produce an error when a Podspec contains an invalid type for the `source` attribute

- CHANGELOG.md
- lib/cocoapods-core/cdn_source.rb
- spec/cdn_source_spec.rb
This PR addresses several issues in `CDNSource`:
1. Thread exhaustion on low-performance machines (such as CI VMs). The default number of threads is now set to 50 with an environment variable allowing to set it differently (`MAX_CDN_NETWORK_THREADS`).
2. Mangled output when concurrent code was failing. Now it will provide a more structured and readable output. Also using `Future`s as apparently this is what the `ruby-concurrent` docs suggest.
3. Non-HTTP errors were raised as exceptions. Now these will be wrapped with data about the specific download.
4. Added retry for network-related errors (`MAX_NUMBER_OF_RETRIES = 5`).
> Improve threading in CDNSource

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/dsl_spec.rb
- spec/podfile/target_definition_spec.rb
With multi-xcodeproj now users can have this option to group pods together. The actual CocoaPods change will follow but it's extremely easy in an internal test I did.
CocoaPods PR https://github.com/CocoaPods/CocoaPods/pull/8939
> Add `project_name` DSL to allow grouping pods into projects.

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/linter.rb
- spec/specification/linter_spec.rb
- spec/specification_spec.rb
Closes CocoaPods/CocoaPods#8785
Output of lint for the example on the above issue will now look like this (a bit ugly, but nicer than a crash)
```
-> SharkORM ({VER})
- ERROR | attributes: Unable to parse attribute `version` due to error: Malformed version number string {VER}
- ERROR | version: Unable to validate due to exception: Malformed version number string {VER}
- ERROR | source: Unable to validate due to exception: Malformed version number string {VER}
- ERROR | attributes: Unable to validate `version` (Malformed version number string {VER}).
- ERROR | [iOS] unknown: Encountered an unknown error (The `SharkORM` pod failed to validate due to 4 errors:
- ERROR | attributes: Unable to parse attribute `version` due to error: Malformed version number string {VER}
- ERROR | version: …
```
> Gracefully handle invalid version strings during linting

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl.rb
This is a supporting PR for the functionality introduced in https://github.com/CocoaPods/cocoapods-downloader/pull/89.
- Add an option `:headers` key for the caller to provide custom headers
> Add headers option on Http download strategy

- lib/cocoapods-core/source/manager.rb
- spec/source/manager_spec.rb
It was adding the trailing slash to the saved URL, but couldn't find it without.
> Fix another trailing slash issue 😂

- lib/cocoapods-core/cdn_source.rb
- spec/cdn_source_spec.rb
I've fixed the flaky tests, ran it many times!
I've also found a small mistake in the repo update code. The repo update process ran `download_file('deprecated_podspecs.txt')` twice which was unnecessary.
> Fix CDNSource tests

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- spec/specification_spec.rb
Came across it when I was trying to multi-thread the Netlify builder. Did not end up needing it, but thought this made sense to PR anyway.
> Don't `Dir.chdir` when loading `Pod::Specification` from JSON

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl.rb
- spec/specification/consumer_spec.rb
- spec/specification/dsl_spec.rb
- spec/specification/json_spec.rb
- spec/specification/linter_spec.rb
Add support for UI test type.
Required for CocoaPods/Cocoapods#9001.
> [DSL] Support for test_type :ui

- lib/cocoapods-core/specification/dsl.rb
Please let me know if my understanding of this is correct! I was having issues because I had added a bunch of headers to `public_header_files` but not to `source_files`, and it wasn't working properly. Also, I wonder if this behavior should be changed somehow, even just adding a warning if it seems like the user is doing the wrong thing.
> Update docs to mention that public header files should be included in source files

- lib/cocoapods-core/specification/consumer.rb
That will now be handled by the xcconfig generator in CocoaPods
For https://github.com/CocoaPods/CocoaPods/pull/9030
> [Consumer] Don't merge non-library spec build settings

- CHANGELOG.md
- lib/cocoapods-core/http.rb
This way a caller, like the social media validator, can specify something different (Issue CocoaPods/CocoaPods#9049)
> Added user_agent argument to http methods

- lib/cocoapods-core/cdn_source.rb
- spec/cdn_source_spec.rb
This PR addresses some reports of encountering reliability problems with CDN servers.  
Generally speaking, ['retry culture'](https://twitter.com/jessfraz/status/1141414897743466496) is not a positive phenomenon and it affects all aspects of modern computing.  
However, in the case of CocoaPods, this was inevitable, since we are free users of the CDNs and can't expect GitHub or Netlify to improve their infrastructure for our benefit.
This PR adds exponential backoff retries for HTTP errors `502`, `503`, `504`. Adding it for other `5xx` errors seemed too heavy-handed.
The total number of retries is configured by the constant `MAX_NUMBER_OF_RETRIES`, or by setting ENV variable `COCOAPODS_CDN_MAX_NUMBER_OF_RETRIES`.
The backoff function is `4 * 2 ^ i`, meaning `4, 8, 16, 32` seconds. …
> CDNSource: Add retries for 502, 503, 504 errors

- lib/cocoapods-core/dependency.rb
- lib/cocoapods-core/specification/root_attribute_accessors.rb
The code path was already defunct* and untested. The todos around this were misleading as not in sync with actual behavior anymore.
*defunct as in dead: the first regex here removes all parentheses, the next tries to match on them.
https://github.com/CocoaPods/Core/blob/065bb3e0576e3bd92d97809018b376572f3d00d2/lib/cocoapods-core/dependency.rb#L368-L370
> Remove legacy code around HEAD dependencies

- lib/cocoapods-core/lockfile.rb
- lib/cocoapods-core/source/manager.rb
- spec/source/manager_spec.rb
Today I looked into what seems like a resolver issue.  
A user that had the old `master` repo still intact reported the fact that some pods were being unlocked in the `Podfile.lock` and reassigned to `master` repo.   
The 'multiple sources' warning was being raised.
Upon researching, it came to light that `Source::Manager` wasn't correctly finding sources by their names, including the `trunk` source.
This PR fixes the behavior and also adds some code comments as to why `TrunkSource` is locked by name.
> Fix Source::Manager#aggregate_for_dependency

- CHANGELOG.md
- lib/cocoapods-core.rb
- lib/cocoapods-core/build_type.rb
- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/podfile/target_definition.rb
- spec/build_type_spec.rb
- spec/fixtures/Podfile_UsesFrameworksBoolean.yaml
- spec/fixtures/Podfile_UsesFrameworksHash.yaml
- spec/podfile/target_definition_spec.rb
- spec/podfile_spec.rb
RFC: https://github.com/CocoaPods/CocoaPods/issues/9099
> Expand `use_frameworks!` DSL to accept linkage style.

- cocoapods-core.gemspec
Closes https://github.com/CocoaPods/CocoaPods/issues/9177
> update concurrent-ruby dep to be ~> 1.1, as that's the one with the new Promises API

- Gemfile.lock
- cocoapods-core.gemspec
- lib/cocoapods-core/cdn_source.rb
- spec/cdn_source_spec.rb
This PR comes to address 3 issues regarding `CDNSource` and its HTTP handling by moving to `Typhoeus`, a `libcurl` wrapper:
The previous implementation utilized 50 threads to make HTTP requests, which was too much/too little for different use cases.  
The new implementation moves all the async code to a single-threaded reactor provided by the [libcurl Multi interface](https://curl.haxx.se/libcurl/c/libcurl-multi.html). This achieves same performance as the multithreaded way.
The built-in `Net::HTTP` module doesn't support HTTP/2, and by extension, `nap` also doesn't.  There are many benefits to HTTP/2, but the relevant to us are reducing the number of connections and reducing bandwidth by compressing headers.
I believe that the time to move to this better-performing implementation is now, …
> Use Typhoeus for more performant CDN requests

- CHANGELOG.md
- lib/cocoapods-core/platform.rb
- spec/platform_spec.rb
This makes it easier for `Platform` consumers to use `Platform.new` to parse values from JSON, Info.plist files,  etc. without having to manually map `macos` => `osx` in order for it to successfully match other platforms defined within CocoaPods.
> Make initializing `Platform` with a string 'macos' behave the same as `Platform.macos`

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/linter.rb
- spec/specification/linter_spec.rb
For https://github.com/CocoaPods/CocoaPods/issues/8921
> Add `code_coverage` support for scheme DSL.

- Gemfile.lock
- cocoapods-core.gemspec
- lib/cocoapods-core/cdn_source.rb
Replace URI.encode with Addressable gem to fix warning when running the latest stable release for CocoaPods on Ruby 2.7.0.
> Replace URI.encode (obsolete) with Addressable gem

- lib/cocoapods-core/version.rb
- spec/version_spec.rb
According to the [semver](https://semver.org/), metadata could contain ASCII alphanumerics. That make `Pod::Version` method `prerelease?` regard version like '1.1.0+exp.1' as a prerelease version.
> [Pod::Version prerelease?] Not correct when version with metadata.

- .travis.yml
- spec/standard_error_spec.rb
2.7.0 is stable now, and it included some deprecation that spawned other PRs
There was a suggestion to add support here: https://github.com/CocoaPods/Core/pull/613#issuecomment-580571457
> Add ruby 2.7.0 support to CI

- CHANGELOG.md
- lib/cocoapods-core/podfile.rb
- lib/cocoapods-core/podfile/dsl.rb
- spec/podfile_spec.rb
Create a post_integrate API, with this we are able to add a scripts to execute after the project are generated, like:
```ruby
post_integrate do |installer|
puts "Called"
bricklayer.configure_project
end
```
obs: `bricklayer` is my own package to link and compile project subproject's, for execute this I need the `.xcworkspace` file already created
Ref. [#7432](https://github.com/CocoaPods/CocoaPods/issues/7432#issuecomment-561745032)
Impl. [#9391](https://github.com/CocoaPods/CocoaPods/pull/9391)
> Add a post integrate hook

- Gemfile
- Gemfile.lock
- lib/cocoapods-core/specification/linter.rb
Fixes some warnings by upgrading `rake` gem and also a warning during running a single test.
> Ruby 2.7.x clear remaining warnings during tests.

- lib/cocoapods-core/specification/linter.rb
- spec/specification/linter_spec.rb
This checks that vendored libraries match the expected format `lib[name].a`.
This comes up occasionally in issues, such as https://github.com/CocoaPods/CocoaPods/issues/9596
> Add a lint check for the name format of vendored static libraries

- CHANGELOG.md
- lib/cocoapods-core/cdn_source.rb
- spec/cdn_source_spec.rb
Write the file from CDN to disk without any conversions.
Some `response_body` are coming back with encoding=`ASCII-8BIT` but are not writable to
disk, with errors like this:
```
[!] CDN: trunk Repo update failed - 31 error(s):
"\xE2" from ASCII-8BIT to UTF-8
```
(second line repeated 31 times)
- Cocoapods 1.9.1
- Ruby 2.5.3, and Ruby 2.7.1 both via `rvm`
- MacOS 10.14.6
Env vars: 
- `LANG=en_US.UTF-8`
Here is the stacktrace from `pod install --verbose`
```
$HOME/.rvm/gems/ruby-2.5.3/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:479:in `rescue in concurrent_requests_catching_errors'
$HOME/.rvm/gems/ruby-2.5.3/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:474:in `concurrent_requests_catching_errors'
$HOME/.rvm/gems/ruby-2.5.3/gems/cocoapods-core-1.9.1/lib/cocoapods- …
```
> Force UTF-8 encoding on JSON Podspecs

- lib/cocoapods-core/podfile/dsl.rb
Following https://github.com/CocoaPods/guides.cocoapods.org/pull/190, provide an example for `~> 0`, to help with this edge case.
> Podfile DSL: Provide example for ~> 0 operator

- CHANGELOG.md
- lib/cocoapods-core/cdn_source.rb
- spec/cdn_source_spec.rb
* Use a robust local check (file exists and is nonzero length) to ensure it's okay.
* Use same check to decide whether to use eTag (so that if file doesn't exist the eTag is disregarded).
Possibly closes https://github.com/CocoaPods/CocoaPods/issues/9814
> CDNSource - Run a rudimentary local check to help with CDN client robustness

- CHANGELOG.md
- Gemfile.lock
- lib/cocoapods-core/gem_version.rb
There were no bug fixes or changes for 1.10.0.beta.2 of Core gem.
> Merge `1-10-stable` (1.10.0.beta.2) into `master`

- CHANGELOG.md
- lib/cocoapods-core/specification/linter.rb
- spec/specification/linter_spec.rb
- spec/version_spec.rb
In React and React Native, nightly builds are created using a version like `0.0.0-githash`. Trying to install such versions with CocoaPods currently fails due to this linter check.
I wasn't able to find a rationale for not allowing version `0` nor could I come up with a reason for not allowing it.
See:
* https://github.com/microsoft/react-native-macos/issues/620
* https://github.com/facebook/react-native/issues/30036
> [Linter] Allow version `0` to be used.

- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/target_definition_spec.rb
```
TypeError - no implicit conversion of Array into String
/Users/JaminZhou/.rvm/gems/ruby-2.6.3/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile/target_definition.rb:920:in `+'
/Users/JaminZhou/.rvm/gems/ruby-2.6.3/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile/target_definition.rb:920:in `block in configuration_pod_whitelist'
/Users/JaminZhou/.rvm/gems/ruby-2.6.3/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile/target_definition.rb:920:in `merge'
/Users/JaminZhou/.rvm/gems/ruby-2.6.3/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile/target_definition.rb:920:in `configuration_pod_whitelist'
/Users/JaminZhou/.rvm/gems/ruby-2.6.3/gems/cocoapods-core-1.7.5/lib/cocoapods-core/podfile/target_definition.rb:476:in `all_whitelisted_configurations' …
```
> fix hash array merge

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl.rb
- spec/specification/dsl_spec.rb
See also https://github.com/CocoaPods/CocoaPods/pull/10207
> Update comments/docs to indicate `module_map=false` will skip `modulemap` file generation

- CHANGELOG.md
- lib/cocoapods-core/podfile.rb
- lib/cocoapods-core/podfile/dsl.rb
- spec/podfile_spec.rb
Add support for a `pre-integrate` hook that will allow plugins to make changes to downloaded pods before the integration into projects.
This is useful for a plugin such as a `cocoapods-patch` that allows users to create patch files for pod dependencies.. whose changes might include a file deletion (which needs to happen before the integration to not cause problems).
CocoaPods PR: https://github.com/CocoaPods/CocoaPods/pull/9935
> Add pre-integrate hook

- Gemfile
- Gemfile.lock
- lib/cocoapods-core/source/manager.rb
Same as https://github.com/CocoaPods/CocoaPods/pull/10347
It looks like we no longer need that fork, trying to remove it
> Use Ruby bundled json gem instead of forked

- .github/workflows/Specs.yml
- .gitignore
- .rubocop.yml
This PR aims to homogenize the way gems are installed in GH Actions and the M1 agent (#672).
The gems will now be installed in `vendor/bundle` and the various ignores have been updated to ignore it.
> Use vendor/bundle in CI

- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/linter.rb
- lib/cocoapods-core/specification/root_attribute_accessors.rb
- spec/specification/dsl_spec.rb
- spec/specification/linter_spec.rb
- spec/specification/root_attribute_accessors_spec.rb
This change adds support and documentation for new optional `readme` and `changelog` attributes, which contain URLs pointing to Markdown files. The CocoaPods Metadata Service has already been modified to read these attributes and, if present, download the files and save them for rendering on the pod page (see https://github.com/CocoaPods/cocoapods-metadata-service/pull/6 and https://github.com/CocoaPods/cocoapods-metadata-service/pull/20).
> Add support for readme and changelog pod attributes

- .github/workflows/Specs.yml
Set `fail-fast` to false so that all specs run and output errors.
> Set `fail-fast` to false

- lib/cocoapods-core/source/manager.rb
- spec/source/manager_spec.rb
This PR tries to simplify the way that a spec repo URL is converted to a repo name. 
The main cases covered:
* GitHub URL: `https://github.com/Orgname/Specs.git` => `orgname`
* Non-GH URL: `https://sourceforge.org/Orgname/Specs.git` => `sourceforge-orgname`
* SCP-style URL: `git@github.com/Orgname/Specs` => `orgname`
* File URL: `file:///Users/username/specs` => `users-username`
* Other odd URLs, such as `ssh://user@companyalias/pod-specs`
* If the repo isn't named `Specs`: `https://github.com/Username/banana.git` => `username-banana`
> Normalize spec repo name generation

- lib/cocoapods-core/source/manager.rb
- spec/source/manager_spec.rb
The "username" doesn't always have to be `git`
> Support GitHub org-style URLs in source manager

- lib/cocoapods-core/cdn_source.rb
Addresses https://github.com/CocoaPods/CocoaPods/issues/10078#issuecomment-818435857
Backports https://github.com/CocoaPods/Core/pull/679 to stable branch
> support 302 redirect

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl.rb
- spec/podfile/target_definition_spec.rb
- spec/specification/consumer_spec.rb
- spec/specification/linter_spec.rb
For https://github.com/CocoaPods/CocoaPods/issues/10770
> Add `before_headers` and `after_headers` execution position DSL

- CHANGELOG.md
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- spec/specification/consumer_spec.rb
- spec/specification/dsl_spec.rb
related https://github.com/CocoaPods/CocoaPods/issues/9820
> Add `project_header_files` DSL to specifications.

- lib/cocoapods-core/specification/linter.rb
- spec/specification/linter_spec.rb
This functionality is being removed from Core and instead is moving to CocoaPods under the `validator.rb` because the validator can actually use the expanded paths.
This will allow developers again to be able to use globs in the DSL for `vendored_libraries`.
see https://github.com/CocoaPods/CocoaPods/pull/10832
> Remove vendored libraries name validation.

- CHANGELOG.md
- lib/cocoapods-core/source/manager.rb
- spec/source/manager_spec.rb
closes https://github.com/CocoaPods/Core/issues/702
@igor-makarov how does this look? See https://rubular.com/r/9pjNikg91btZip for testing.
> Update repo regex to better handle ssh URLs.

- CHANGELOG.md
- lib/cocoapods-core/dependency.rb
`dependency.rb` has a few warnings that are showing up locally and in CI when `pod lib lint`ing. 
For example, see https://github.com/firebase/firebase-ios-sdk/runs/5619185788?check_suite_focus=true.
1. `warning: method redefined; discarding old ...`
```
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/dependency.rb:117: warning: method redefined; discarding old specific_version=
```
2. ` warning: instance variable ... not initialized`
```
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/dependency.rb:112: warning: instance variable @specific_requirement not initialized
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/dependency.rb:133: warning: instance variable @external_source not initialized
```
cc: …
> Fix warnings in `dependency.rb`

- Gemfile.lock
- cocoapods-core.gemspec
:wave: I maintain a tool called [licensed](https://github.com/github/licensed) that enumerates OSS license and other metadata for dependencies used by a project.  We recently added cocoapods and received a [report](https://github.com/github/licensed/issues/609) that the `activesupport < 7` requirement from this gem was causing a user to be unable to upgrade to the latest version of licensed.
Would you consider updating the activesupport requirement to `<8` to support users that want to use this gem in conjunction with rails 7?  I _think_ this change should be ok?  It looks like the gem was only used to add indifferent access support for hashes so the impact would be minimal, and I ran the test suite with `bundle exec rake spec` and everything passed.
> Bump activesupport requirement to < 8

- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/json.rb
- spec/specification/json_spec.rb
Definitely in the top 5 of issues we get which are pretty much unactionable are ones where JSON isn't parsed, so now we give the path to the file in the error message so its more likely people will try and solve themselves instead of making an issue
> Give the pathname for failed json podspecs in the error

- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/linter.rb
- spec/specification/linter_spec.rb
Hi!
In our team we are using CocoaPods in a highly-modularized project and we recently came across a need to specify custom build configurations for autogenerated XCSchemes, especially we want to use custom debug config for some of the schemes and a custom test build config for our unit-tests.
We were surprised when found that this option is not supported, however [Xcodeproj](https://www.rubydoc.info/github/CocoaPods/Xcodeproj/Xcodeproj/XCScheme/AbstractSchemeAction) seems to support this.
Further investigation turns out, this is quite a simple feature, so here we are!
If you have any questions, feel free to ask!
This is the precondition for https://github.com/CocoaPods/CocoaPods/pull/11611
> Added support for specifying build configurations for schemes

- lib/cocoapods-core/yaml_helper.rb
- spec/yaml_helper_spec.rb
With Ruby 3.1, psyche uses safe_load by default. This prevents YAML timestamps from loading as they are not serialized as strings.
- Add the YAML timestamp regex to the list of RESOLVED_TAGS so that tags which look like timestamps are serialized as strings.
- Switch load_string to use YAML.safe_load so that the behavior is consistent between Ruby (psyche) versions.
- Add Date, Time, and Symbol as permitted_classes so that previously serialized  Podfile.lock files can be loaded.
References:
- https://yaml.org/type/timestamp.html
- https://github.com/ruby/psych/commit/176494297f3f124467a6e3f1c9e6400ee742d663
- https://stackoverflow.com/questions/71332602/upgrading-to-ruby-3-1-causes-psychdisallowedclass-exception-when-using-yaml-lo
> [YAMLHelper] Handle YAML timestamps

- CHANGELOG.md
- lib/cocoapods-core/platform.rb
- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/podfile/target_definition.rb
- lib/cocoapods-core/specification/dsl.rb
- spec/platform_spec.rb
- spec/specification/dsl_spec.rb
- spec/specification/json_spec.rb
- spec/specification/linter_spec.rb
This PR introduces `visionOS` as a supported platform in Core. This primarily involves making the DSL helpers accessible for this platform.  This lays the groundwork for supporting visionOS as a new platform in CocoaPods.
Related to https://github.com/CocoaPods/CocoaPods/issues/11961, https://github.com/CocoaPods/Xcodeproj/pull/913 and https://github.com/CocoaPods/CocoaPods/pull/11965
> Add `visionos` as a new platform

- CHANGELOG.md
- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/specification/dsl.rb
- spec/podfile/target_definition_spec.rb
- spec/specification/linter_spec.rb
Exposes existing `PBXShellScriptBuildPhase` attribute for enabling it in cases where it input & output file(s) are not possible to be defined.
Without it, Xcode will always give build time warning about missing inputs & outputs.
Related to: https://github.com/CocoaPods/CocoaPods/pull/12055
> Add support for always_out_of_date flag in script phase

- lib/cocoapods-core/specification/json.rb
- spec/specification/json_spec.rb
Cherry pick of https://github.com/CocoaPods/Core/pull/759 onto master
> Fix an issue that sometimes caused Pod::Version instances to be serialized as a hash inside the :source hash

- lib/cocoapods-core/lockfile.rb
- spec/lockfile_spec.rb
Probably not the best ruby code since I don't actively develop in ruby.
When doing pod install with a Podfile.lock already created, some of the spec repos might be skipped because the key already exists
Fixes #748
> fix missing spec repos

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- spec/specification_spec.rb
When install a subspec such as `AFNetworking/Reachability` with no version range is specified:
```ruby
pod 'AFNetworking/Reachability'
```
Cocoapods will crashed:
```
NoMethodError - undefined method `downcase' for nil:NilClass
```
Same issue mentioned here: https://github.com/CocoaPods/CocoaPods/issues/11733
---
After some research, I found it caused by [AFNetworking (= 1.1.1)](https://github.com/CocoaPods/Specs/blob/master/Specs/a/7/5/AFNetworking/1.1.1/AFNetworking.podspec.json), this `podspec.json` has empty contents:
```json
{
"deprecated_in_favor_of": "Alamofire",
"platforms": {
"osx": null,
"ios": null,
"tvos": null,
"watchos": null
}
}
```
so I add some check code in `subspec_by_name` method, and now no more crash occurs.
> Fix crash when retrieve subspec from a unavailable podspec file

- .github/workflows/Specs.yml
- lib/cocoapods-core/cdn_source.rb
- spec/cdn_source_spec.rb
Allows to declare multiple CDN sources in your Podfile, even if one of them does not fully mirror the trunk.
Removes the requirement to provide empty shards for the version metadata files of non-existing pods on a CDN repo.
Prevents errors like:
```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/nathan/.cocoapods/repos/pods-private/all_pods_versions_4_0_1.txt
```
Fixes #768 
Fixes https://github.com/CocoaPods/CocoaPods/issues/12338
> Support multiple CDN sources

- CHANGELOG.md
- lib/cocoapods-core/cdn_source.rb
Introducing `COCOAPODS_CDN_MAX_CONCURRENCY` configuration point to reduce the maximum concurrency of Hydra. The default max concurrency (200) can lead to flakiness like DNS resolution failure being marked as DoS attack OR missing authorization headers. This flakiness is also remarked in the documentation of [typhoeus library](https://github.com/typhoeus/typhoeus?tab=readme-ov-file#specifying-max-concurrency).
> Allow configuring CDN requests max concurrency to reduce flakiness
