CocoaPods/Core

- lib/cocoapods-core/vendor.rb
- lib/cocoapods-core/vendor/requirement.rb
- lib/cocoapods-core/vendor/version.rb
- lib/cocoapods-core/version.rb
- spec/dependency_spec.rb
- spec/version_spec.rb
I also ran the `CocoaPods` specs and they all passed.
\c @kylef
> [Vendor] Update Gem::Version & Gem::Requirement

- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/dsl_spec.rb
- spec/podfile/target_definition_spec.rb
See https://github.com/CocoaPods/Core/pull/234/files#r27783874
> [TargetDefinition] Don't include current dependency when using subspecs

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/linter.rb
- lib/cocoapods-core/specification/root_attribute_accessors.rb
- spec/specification/dsl_spec.rb
- spec/specification/linter_spec.rb
- spec/specification/root_attribute_accessors_spec.rb
> [Specification] Allow specifying a custom module map file

- lib/cocoapods-core/podfile/dsl.rb
Belongs to CocoaPods/CocoaPods#3649.
> Adapt to the removal of the Hooks-API representation layer

- CHANGELOG.md
- lib/cocoapods-core/podfile.rb
- spec/podfile_spec.rb
how terrible of an idea is this?
\c @neonichu @alloy @indirect
> [Podfile] Sub out smart quotes

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/consumer.rb
- spec/specification_spec.rb
> [Specification] Strip string values when writing with the DSL

- lib/cocoapods-core/platform.rb
- lib/cocoapods-core/specification/dsl.rb
Needed for the [Podspec syntax guide](https://guides.cocoapods.org/syntax/podspec.html#watchos).
/c @neonichu @orta
> [Doc] Add comments for watchos

- lib/cocoapods-core/podfile/dsl.rb
See: https://twitter.com/rkeniger/status/625545721006022657
https://guides.cocoapods.org/syntax/podfile.html
> Fix the inline documentation for a post install example

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/fixtures/podfile_without_root_podspec/Podfile
- spec/podfile/target_definition_spec.rb
> Gracefully handle missing root podspec when auto-detecting

- CHANGELOG.md
- lib/cocoapods-core/yaml_helper.rb
- spec/yaml_helper_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/3907.
\c @alloy
> [YAMLHelper] Allow serializing objects of arbitrary classes

- lib/cocoapods-core/specification/dsl.rb
Closes #4100 in CocoaPods/CocoaPods
> Clarify the pod spec concerning which headers will be considered public

- CHANGELOG.md
- lib/cocoapods-core/lockfile.rb
- spec/lockfile_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/3999.
\c @orta @kylef
> [Lockfile] Store the checksum of the Podfile

- CHANGELOG.md
- lib/cocoapods-core/version.rb
- spec/dependency_spec.rb
Closes CocoaPods/CocoaPods#4365.
\c @floere
> [Version] Compare differently for sorting and equality

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/target_definition_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/3605.
> [TargetDefinition] Inherit whitelisted configurations

- CHANGELOG.md
- lib/cocoapods-core/platform.rb
- spec/platform_spec.rb
> Add ability to get all platforms

- CHANGELOG.md
- lib/cocoapods-core/specification/json.rb
- spec/specification/json_spec.rb
Closes #267. 
\c @alloy @neonichu @orta
> [JSON] Serialize default platforms when converting to JSON

- lib/cocoapods-core/specification/json.rb
- spec/specification/json_spec.rb
> [JSON] Fix platform serialization to handle inheritance

- CHANGELOG.md
- lib/cocoapods-core/lockfile.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/root_attribute_accessors.rb
- spec/specification/dsl_spec.rb
- spec/specification/root_attribute_accessors_spec.rb
> [Specification::DSL] Remove docset_url attribute

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/dsl_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/4707.
\c @keith
> [TargetDefinition] Fix whitelisting pods in non-root targets

- CHANGELOG.md
- lib/cocoapods-core/dependency.rb
Closes CocoaPods/CocoaPods#4710.
\c @orta
> [Dependency] Allow creating from a string that has HEAD info

- CHANGELOG.md
- lib/cocoapods-core/podfile.rb
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/standard_error.rb
- spec/standard_error_spec.rb
We should not show the update suggestion on argument errors.
> [DSLError] Do not show update suggestion on argument errors

- lib/cocoapods-core/podfile/dsl.rb
closes https://github.com/CocoaPods/CocoaPods/issues/4799
> Fix typo in documentation

- lib/cocoapods-core/standard_error.rb
- spec/standard_error_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/4800.
\c @orta
> [DSLError] Dont suggest updating CocoaPods

- CHANGELOG.md
- lib/cocoapods-core/podfile/dsl.rb
- spec/podfile/dsl_spec.rb
- spec/podfile_spec.rb
> [DSL] Rename xcodeproj to project

- lib/cocoapods-core/podfile/dsl.rb
> Podfile DSL Docs improvements

- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/specification/dsl.rb
> [Doc] Minor fix & consistent quoting style

- lib/cocoapods-core/platform.rb
- spec/dependency_spec.rb
- spec/platform_spec.rb
- spec/specification/json_spec.rb
Nice to have for https://github.com/CocoaPods/CocoaPods/pull/4146.
/c @segiddins.
> [Platform] Add convenience methods to access string name

- lib/cocoapods-core/podfile/dsl.rb
Addresses [#4866](https://github.com/CocoaPods/CocoaPods/issues/4866#issuecomment-182354435)
> [Docs] Clarifies deprecated methods in docs

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/target_definition_spec.rb
Fixes https://github.com/CocoaPods/CocoaPods/issues/4943.
> [TargetDefinition] Allow grandchildren to inherit parents search paths

- CHANGELOG.md
- lib/cocoapods-core/yaml_helper.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/4740.
\c @floere
> [YAMLHelper] Ensure the YAML doesnt have preceding >-

- .travis.yml
- Gemfile
- Gemfile.lock
Makes sense to also test against the latest ruby
> [Travis] Also test against Ruby 2.3.0

- lib/cocoapods-core/source.rb
Potentially closes https://github.com/CocoaPods/CocoaPods/issues/5039.
> [Source] Improve check for being in the repo root

- lib/cocoapods-core/podfile/dsl.rb
Addresses https://github.com/CocoaPods/CocoaPods/issues/4700 with some nicer wording :+1:
> Improve documentation around the configuration options for a Podfile

- lib/cocoapods-core/vendor.rb
- lib/cocoapods-core/vendor/requirement.rb
- lib/cocoapods-core/vendor/version.rb
This mainly pulls in performance enhancements to version comparisons
> [Vendor] Update Gem::Version & Gem::Requirement to 2.6.3

- CHANGELOG.md
- lib/cocoapods-core/specification/dsl/attribute.rb
- spec/specification/dsl/attribute_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/5177
> [Attribute] Root attributes are inherited by default

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/target_definition_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/5242
\c @mrackwitz
> [TargetDefinition] Match platforms with an abstract target with no platform

- CHANGELOG.md
- lib/cocoapods-core/source.rb
Fixes cocoapods/cocoapods#5039.
> Fixed path checking.

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/5379
> [TargetDefinition] Return nil when storing a pod

- CHANGELOG.md
- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/dsl_spec.rb
> [Podfile] Disallow setting a target's platform twice

- lib/cocoapods-core/podfile/dsl.rb
I was looking for a working substitute for http://docs.rubygems.org/read/chapter/7 but nothing stuck out -  I'm open to suggestions.
> [Podfile DSL Docs] Various fixes

- lib/cocoapods-core/podfile.rb
Most of this was capitalization consistency, but also some rephrasing.
> [Docs] Podfile

- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/target_definition_spec.rb
Required for https://github.com/CocoaPods/CocoaPods/pull/5540
> [TargetDefinition] Add swift_version to target_definition

- lib/cocoapods-core/podfile/target_definition.rb
`version` 's type is maybe `String`.
Please review this PR, thank you.
> Fix typo in comment

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- spec/specification_spec.rb
Completes https://github.com/CocoaPods/CocoaPods/issues/5180
Improvement in our large project is about 10%-12% for `pod install`
@segiddins let me know if there is a better way to do this or anything I forget regarding invalidating this value.
> Cache specification hash value

- lib/cocoapods-core/podfile.rb
I was confused by the original messaging. To me, it implied that the `Podfile` would be saved with the sanitization, which did not happen. Not sure this how others might read it, so open to suggestions here.
> Update smart quotes warning

- CHANGELOG.md
- lib/cocoapods-core/platform.rb
- lib/cocoapods-core/podfile/target_definition.rb
- lib/cocoapods-core/specification/dsl.rb
- spec/platform_spec.rb
- spec/specification/dsl_spec.rb
- spec/specification/set/presenter_spec.rb
> Support using macos as an alias for osx

- lib/cocoapods-core/specification/dsl.rb
> Add example showing the usage of `weak_frameworks`

- CHANGELOG.md
- lib/cocoapods-core/podfile/dsl.rb
PR for issue #7359 addressing some missing documentation.
> Add missing documentation to Podfile Reference Guide #7359

- lib/cocoapods-core/lockfile.rb
- lib/cocoapods-core/yaml_helper.rb
- spec/lockfile_spec.rb
- spec/yaml_helper_spec.rb
For https://github.com/CocoaPods/CocoaPods/pull/7358
> [Lockfile] Store what spec repo a pod comes from

- CHANGELOG.md
- lib/cocoapods-core/lockfile.rb
- spec/lockfile_spec.rb
closes https://github.com/CocoaPods/CocoaPods/issues/7586
> Lowercase spec repos

- lib/cocoapods-core/specification/dsl.rb
It's under `File Patterns` now which doesn't make sense.
> Move script phases DSL under build settings group

- lib/cocoapods-core/lockfile.rb
- lib/cocoapods-core/master_source.rb
- lib/cocoapods-core/source.rb
- lib/cocoapods-core/source/manager.rb
Follow up on https://github.com/CocoaPods/CocoaPods/issues/7586
> Only lowercase the master specs repo for lockfile

- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/podfile/target_definition.rb
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/root_attribute_accessors.rb
- spec/podfile/target_definition_spec.rb
- spec/specification/dsl_spec.rb
- spec/specification/json_spec.rb
- spec/specification/root_attribute_accessors_spec.rb
DSL changes for https://github.com/CocoaPods/CocoaPods/issues/8191
> Update `swift_version` DSL to support multiple versions and filtering

- lib/cocoapods-core/podfile.rb
- spec/podfile_spec.rb
For https://github.com/CocoaPods/CocoaPods/issues/8171
> [Podfile] Add support for `Podfile.rb` file name

- CHANGELOG.md
- lib/cocoapods-core/podfile/target_definition.rb
- spec/podfile/dsl_spec.rb
> [Podfile] Allow `inhibit_all_warnings!` in parent and child scopes

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/linter.rb
- spec/specification/consumer_spec.rb
- spec/specification/dsl_spec.rb
- spec/specification/json_spec.rb
- spec/specification/linter/analyzer_spec.rb
- spec/specification/linter_spec.rb
For https://github.com/CocoaPods/CocoaPods/issues/7577
PR in CocoaPods: https://github.com/CocoaPods/CocoaPods/pull/8347
> DSL for `scheme` support

- CHANGELOG.md
- lib/cocoapods-core/specification/linter.rb
- spec/specification/linter_spec.rb
minor follow up on https://github.com/CocoaPods/Core/pull/475
> Prevent subspecs from specifying scheme configuration

- lib/cocoapods-core/podfile/dsl.rb
I saw this [on the guides](https://guides.cocoapods.org/syntax/podfile.html) so I opened a PR.
> Updates inherited target quote style

- lib/cocoapods-core/podfile/dsl.rb
Closes https://github.com/CocoaPods/guides.cocoapods.org/issues/150
> Fix incorrect linebreak on Podfile #source documentation

- .travis.yml
- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/cocoapods-core/source/manager.rb
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/json.rb
- spec/fixtures/spec-repos/test_repo/Specs/BananaLib/1.1/BananaLib.podspec
- spec/source/health_reporter_spec.rb
- spec/specification/linter_spec.rb
Includes the changes in https://github.com/CocoaPods/Core/pull/522
cc @dostrander
> Fix linting a JSON podspec that contains test/app subspecs

- lib/cocoapods-core/source/manager.rb
- spec/source/manager_spec.rb
replace the pr https://github.com/CocoaPods/Core/pull/524#event-2251637483
> delete search index json file when parsing failed

- lib/cocoapods-core/dependency.rb
- lib/cocoapods-core/version.rb
> Fix memoizing the #prerelease? method when it returns false

- lib/cocoapods-core/dependency.rb
- spec/dependency_spec.rb
Also add tests so we dont regress again
> [Dependency] Fix #prerelease?

- CHANGELOG.md
- lib/cocoapods-core/source/metadata.rb
- spec/source/metadata_spec.rb
Closes https://github.com/CocoaPods/Core/issues/482
> [Source] Fix a crash when searching for compatible versions

- CHANGELOG.md
- lib/cocoapods-core/specification/consumer.rb
- spec/specification/consumer_spec.rb
closes CocoaPods/CocoaPods#8776
cherry-pick commit a2f58b0ab49570b1f675a2aeed12089694caa4ec
> Cherry-pick #504 to 1.6.x

- CHANGELOG.md
- lib/cocoapods-core/specification/json.rb
- lib/cocoapods-core/specification/linter/analyzer.rb
- spec/specification/json_spec.rb
Closes https://github.com/CocoaPods/CocoaPods/issues/8635
> Ensure `swift_version` singular version is included in JSON representation.

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/linter.rb
- spec/specification/consumer_spec.rb
- spec/specification/dsl_spec.rb
- spec/specification/json_spec.rb
- spec/specification/linter_spec.rb
Progress towards https://github.com/CocoaPods/CocoaPods/issues/8753
> Add Info.plist DSL to Podspecs

- lib/cocoapods-core/specification.rb
- spec/specification_spec.rb
Fixes a regression caused by #555
> Fix an issue preventing #to_s from including the version for subspecs

- lib/cocoapods-core/cdn_source.rb
- spec/cdn_source_spec.rb
Extra logging for: https://github.com/CocoaPods/CocoaPods/issues/8987
> Add more logging to CDN source

- lib/cocoapods-core/cdn_source.rb
- spec/cdn_source_spec.rb
#559 was a step in the right direction, however there are a few more additions to it that are needed:
* The actual wording of the messages didn't reflect the data presented.
* There was one other case that wasn't covered.
* Redirect message wasn't consistent with other messages or being tested.
> Improve CDN error reporting

- Gemfile.lock
- cocoapods-core.gemspec
- lib/cocoapods-core/cdn_source.rb
- lib/cocoapods-core/source.rb
- lib/cocoapods-core/source/manager.rb
- spec/cdn_source_spec.rb
- spec/fixtures/mock_cdn_repo_remote/AlgoliaSearch.yml
- spec/source/manager_spec.rb
- spec/source_spec.rb
Complementary to https://github.com/CocoaPods/CocoaPods/pull/9046
> Allow Algolia search for CDNSource

- lib/cocoapods-core/podfile/dsl.rb
> Move `supports_swift_version` DSL under "Target Configuration" group

- CHANGELOG.md
- lib/cocoapods-core/podfile/dsl.rb
- lib/cocoapods-core/podfile/target_definition.rb
- lib/cocoapods-core/specification/dsl.rb
- spec/podfile/target_definition_spec.rb
- spec/specification/linter_spec.rb
For https://github.com/CocoaPods/CocoaPods/issues/9082
> Extend `script_phase` DSL to support dependency file.

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/linter/analyzer.rb
- spec/specification/dsl_spec.rb
- spec/specification/json_spec.rb
- spec/specification_spec.rb
Goes with https://github.com/CocoaPods/CocoaPods/pull/9149
> Add `:configurations` DSL for podspec dependencies.

- CHANGELOG.md
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/dsl/attribute_support.rb
- spec/specification/dsl_spec.rb
- spec/specification/json_spec.rb
- spec/specification_spec.rb
closes https://github.com/CocoaPods/Core/issues/584
> Allow specifying no default subspecs

- lib/cocoapods-core/cdn_source.rb
Also https://github.com/CocoaPods/CocoaPods/pull/9447
> Lazy require Typhoeus because its load takes 300ms

- lib/cocoapods-core/specification/dsl.rb
For https://github.com/CocoaPods/CocoaPods/issues/9559
> Clarify that vendored libraries & frameworks will be exposed to pod consumers in docs

- CHANGELOG.md
- lib/cocoapods-core/podfile/dsl.rb
- spec/podfile/dsl_spec.rb
closes CocoaPods/CocoaPods#9325
> [DSL] Add ensure_bundler! flag

- lib/cocoapods-core/cdn_source.rb
> handle http/302 like 301 during download_and_save_with_retries_asynch

- lib/cocoapods-core/cdn_source.rb
adding to 1-10-stable branch to allow for adding the change to 1.10.2
>  handle http/302 like 301 during download_and_save_with_retries_asynch

- CHANGELOG.md
- Gemfile.lock
- cocoapods-core.gemspec
For https://github.com/CocoaPods/CocoaPods/issues/10802
> Bump addressable dependency to 2.8.

- CHANGELOG.md
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/linter/analyzer.rb
- spec/specification/consumer_spec.rb
- spec/specification/dsl_spec.rb
- spec/specification/linter/analyzer_spec.rb
supersedes https://github.com/CocoaPods/Core/pull/622
> Add support for `on_demand_resources` DSL.

- lib/cocoapods-core/cdn_source.rb
- lib/cocoapods-core/dependency.rb
- lib/cocoapods-core/github.rb
- lib/cocoapods-core/lockfile.rb
- lib/cocoapods-core/platform.rb
- lib/cocoapods-core/podfile.rb
- lib/cocoapods-core/podfile/target_definition.rb
- lib/cocoapods-core/requirement.rb
- lib/cocoapods-core/source.rb
- lib/cocoapods-core/source/manager.rb
- lib/cocoapods-core/source/metadata.rb
- lib/cocoapods-core/specification.rb
- lib/cocoapods-core/specification/consumer.rb
- lib/cocoapods-core/specification/dsl.rb
- lib/cocoapods-core/specification/dsl/attribute.rb
- lib/cocoapods-core/specification/linter.rb
- lib/cocoapods-core/specification/root_attribute_accessors.rb
- lib/cocoapods-core/version.rb
This PR is related to https://github.com/CocoaPods/CocoaPods/pull/10924
> Replace [Bool] with [Boolean] according to the YARD convention.

- lib/cocoapods-core/podfile/dsl.rb
For page:
https://guides.cocoapods.org/syntax/podfile.html#source
> use CDN source in example

- lib/cocoapods-core/specification.rb
This is faster and reduces memory allocations
> Optimize Specification.root_name

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/cocoapods-core.rb
Fixes https://github.com/CocoaPods/CocoaPods/issues/12116
> Fix a crash when running with specific versions of activesupport

- lib/cocoapods-core/platform.rb
Fix https://github.com/CocoaPods/CocoaPods/issues/12109
> Aligning platform information between XCFramework and Cocoapods.

- lib/cocoapods-core/version.rb
- spec/version_spec.rb
> Fix semantic version comparison for mixed numeric and string prerelease segments
